services:
  falcon:
    build:
      context: ./
      network: host
    network_mode: host
    environment:
      - "FALCON__SERVER__HOST=${FALCON__SERVER__HOST:-0.0.0.0}"
      - "FALCON__SERVER__PORTS__PUBLIC=${FALCON__SERVER__PORTS__PUBLIC:-20100}"
      - "FALCON__SERVER__PORTS__ADMIN=${FALCON__SERVER__PORTS__ADMIN:-20101}"
      - "FALCON__URLS__PUBLIC=${FALCON__URLS__PUBLIC:-http://localhost:20100}"
      - "FALCON__URLS__ADMIN=${FALCON__URLS__ADMIN:-http://localhost:20101}"
      - "FALCON__COOKIES__DOMAIN=${FALCON__COOKIES__DOMAIN:-}"
      - "FALCON__SECRETS__DEFAULT=${FALCON__SECRETS__DEFAULT:-XXXXXXXXXXXXXXXX}"
      - "FALCON__SECRETS__COOKIE=${FALCON__SECRETS__COOKIE:-XXXXXXXXXXXXXXXX}"
      - "FALCON__SECRETS__CIPHER=${FALCON__SECRETS__CIPHER:-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}"
      - "FALCON__ORCHID__PUBLIC__SCHEME=${FALCON__ORCHID__PUBLIC__SCHEME:-http}"
      - "FALCON__ORCHID__PUBLIC__HOST=${FALCON__ORCHID__PUBLIC__HOST:-localhost}"
      - "FALCON__ORCHID__PUBLIC__PORT=${FALCON__ORCHID__PUBLIC__PORT:-20120}"
      - "FALCON__ORCHID__PUBLIC__PATH=${FALCON__ORCHID__PUBLIC__PATH:-}"
      - "FALCON__OBSIDIAN__SQL__HOST=${FALCON__OBSIDIAN__SQL__HOST:-localhost}"
      - "FALCON__OBSIDIAN__SQL__PORT=${FALCON__OBSIDIAN__SQL__PORT:-20110}"
      - "FALCON__OBSIDIAN__SQL__PASSWORD=${FALCON__OBSIDIAN__SQL__PASSWORD:-password}"
      - "FALCON__OIDC__GOOGLE__CLIENT=${FALCON__OIDC__GOOGLE__CLIENT:-falcon}"
      - "FALCON__OIDC__GOOGLE__SECRET=${FALCON__OIDC__GOOGLE__SECRET:-secret}"
      - "FALCON__OIDC__GOOGLE__DOMAIN=${FALCON__OIDC__GOOGLE__DOMAIN:-}"
      - "FALCON__DEBUG=${FALCON__DEBUG:-true}"
